Mbia 60 scheduler monitor
YotpoLtd/red_cross pull request #11
Opened 2017-02-12 14:33 UTC by dmitri86git

2017-02-12 14:41 UTC, dmitri86git commented
@vladshub Hey, please review

2017-02-13 14:53 UTC, vladshub requested changes

2017-02-13 14:53 UTC, vladshub commented on lib/resque/plugins/red_cross_async.rb
> +        @job_end_time = Time.now().to_f
@dmitri86git this should be 
```ruby
job_end_time = Time.now()
```

2017-02-13 14:53 UTC, vladshub commented on lib/resque/plugins/red_cross_async.rb
> +        @job_start_time = Time.now().to_f
@dmitri86git this should be 
```ruby
job_start_time = Time.now()
```

2017-02-13 14:53 UTC, vladshub commented on lib/resque/plugins/red_cross_async.rb
> +        @job_end_time = Time.now().to_f
@dmitri86git this should be 
```ruby
job_end_time = Time.now()
```

2017-02-13 14:54 UTC, vladshub commented on lib/resque/plugins/red_cross_async.rb
>          {}
@dmitri86git as discussed this should have a filter function for the args hash to make sure it will send only specific parameters.

2017-02-15 16:58 UTC, vladshub requested changes

2017-02-15 16:58 UTC, vladshub commented on lib/red_cross.rb
> +require 'red_cross/resque/plugins/red_cross_monitor'
@dmitri86git please delete this

2017-02-15 16:58 UTC, vladshub commented on lib/red_cross/resque/plugins/red_cross_monitor.rb
> +        if !(@event_properties[:event_method].present?)
```
def default_event_properties(*args)
	@event_properties ||= { fields: {  } }
	@event_properties[:class] ||= self.name
	
	if @event_properties[:event_method].nil?
		ijob_method = job_method(*args)
	else
		ijob_method = @event_properties[:event_method]
	end

	if ijob_method.present? && ([String, Integer, Symbol].include? ijob_method.class)
		@event_properties[:event_method] = ijob_method
	else
		@event_properties[:event_method] = 'not_valid_job_method'
	end
end
```

2017-02-15 16:58 UTC, vladshub commented on lib/red_cross/resque/plugins/red_cross_monitor.rb
> +        #Add the method that triggered by the job
this should return
```
@job_method
```
generally you should define an attribute accessor for job_method

2017-02-16 12:45 UTC, vladshub approved these changes

2017-02-16 12:45 UTC, merged